/* 
 *  application.h
 *
 *  CCC 1/2021
 */

extern volatile unsigned *gpio;

void setup(void);
void finalize(void);

//void received_name(const char *partner, const char *name);
//void received_name_list(const char *partner, const char *name_list);
//void received_error(const char *partner, const char *msg);

void on_mqtt_connected();
void on_mqtt_disconnected();
void on_mqtt_failure(const char *msg);
void on_mqtt_name_arrived(const char *name);

// code generated by preprocessor

void loop1(int period_ms);
